# Singular Value Decomposition (SVD)

links:

https://stats.stackexchange.com/questions/107533/how-to-use-svd-for-dimensionality-reduction-to-reduce-the-number-of-columns-fea

https://www.analyticsvidhya.com/blog/2019/08/5-applications-singular-value-decomposition-svd-data-science/

https://sthalles.github.io/svd-for-regression/

https://towardsdatascience.com/svd-8c2f72e264f

https://towardsdatascience.com/pca-and-svd-explained-with-numpy-5d13b0d2a4d8

https://heartbeat.fritz.ai/recommender-systems-with-python-part-iii-collaborative-filtering-singular-value-decomposition-5b5dcb3f242b

https://stats.stackexchange.com/questions/342046/explaining-dimensionality-reduction-using-svd-without-reference-to-pca

https://www.coryjmaklin.com/least-squares-linear-regression-in-python

https://bigdata-madesimple.com/decoding-dimensionality-reduction-pca-and-svd/

https://en.wikipedia.org/wiki/Singular_value_decomposition

https://blogs.oracle.com/r/using-svd-for-dimensionality-reduction#:~:text=SVD%2C%20or%20Singular%20Value%20Decomposition,columns%2C%20of%20a%20data%20set.&text=While%20SVD%20can%20be%20used,image%20compression%2C%20and%20other%20areas.

http://cs-people.bu.edu/evimaria/cs565-14/dimensionality-reduction.pdf




https://stackoverflow.com/questions/31523575/get-u-sigma-v-matrix-from-truncated-svd-in-scikit-learn/31528944

``` python
svd = TruncatedSVD(k)
X_transformed = svd.fit_transform(X)

U = X_transformed / svd.singular_values_
Sigma_matrix = np.diag(svd.singular_values_)
VT = svd.components_
```

In [2]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

In [117]:
A = np.array([[1,2,3,4,5,6],
             [2,4,6,1,3,1],
             [3,6,9,2,5,1],
             [4,8,12,5,5,5],
             [5,10,15,1,10,1],
             [6,12,18,6,0,5],
             [7,14,21,5,5,3]])
A
np.linalg.matrix_rank(A)

4

In [168]:
svd_trunc = TruncatedSVD(n_components=3, random_state=42)

In [184]:
A_reduced = svd_trunc.fit_transform(A)
A_reduced

array([[ 6.4766594 , -2.65260072,  6.4812963 ],
       [ 8.0921228 , -1.15967761, -0.38588445],
       [12.27702519, -2.14356939, -0.64027441],
       [17.01673911, -0.43111826,  3.03397689],
       [20.30057348, -5.74772029, -2.5866759 ],
       [23.00072996,  5.94287867,  0.73508522],
       [27.19823545,  1.47835318, -1.72874247]])

In [185]:
A_original = svd_trunc.inverse_transform(A_reduced)
A_original

array([[ 0.99749574,  1.99499148,  2.99248722,  4.07707962,  5.01163136,
         5.94319893],
       [ 1.99601412,  3.99202825,  5.98804237,  1.1226829 ,  3.01851293,
         0.90959323],
       [ 3.01342333,  6.02684665,  9.04026998,  1.58683806,  4.9376536 ,
         1.30446488],
       [ 4.00514976,  8.01029951, 12.01544927,  4.84149355,  4.97608128,
         5.11680565],
       [ 4.98967812,  9.97935624, 14.96903435,  1.31770137, 10.04794134,
         0.76588137],
       [ 5.99149699, 11.98299398, 17.97449097,  6.26171757,  0.03949335,
         4.80713662],
       [ 7.00739601, 14.01479202, 21.02218803,  4.77235522,  4.96564826,
         3.16775466]])

In [137]:
U, s, Vh = np.linalg.svd(A)

In [171]:
U.shape, s.shape, Vh.shape

((7, 7), (6,), (6, 6))

In [175]:
r = 3
B1 = np.dot(np.dot(U[:,:r], np.diag(s)[:r,:r]), Vh[:r,:])
B2 = np.dot(U[:,:r], np.diag(s)[:r,:r])

In [189]:
B2, np.linalg.matrix_rank(B2)

(array([[ -6.4766594 ,   2.65260072,   6.4812963 ],
        [ -8.0921228 ,   1.15967761,  -0.38588445],
        [-12.27702519,   2.14356939,  -0.64027441],
        [-17.01673911,   0.43111826,   3.03397689],
        [-20.30057348,   5.74772029,  -2.5866759 ],
        [-23.00072996,  -5.94287867,   0.73508522],
        [-27.19823545,  -1.47835318,  -1.72874247]]),
 3)